# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405
r"""
Simplicial complex construction.

Build Vietoris-Rips complexes from point clouds using matrix-free,
combinatorial-index encoding for memory efficiency.
"""

import builtins
import numpy
import numpy.typing
import typing
__all__ = [
    "VietorisRipsComplex",
]

@typing.final
class VietorisRipsComplex:
    r"""
    A Vietoris-Rips simplicial complex built from a point cloud.
    
    The Vietoris-Rips complex is constructed by adding a k-simplex for every
    set of (k+1) points that are pairwise within the given distance threshold.
    It is the standard construction used in topological data analysis to study
    the shape of data.
    
    Parameters
    ----------
    points : numpy.ndarray
        Input point cloud of shape ``(n_points, n_features)``.
    max_dim : int, optional
        Maximum simplex dimension to construct (default ``2``).
    threshold : float or None, optional
        Maximum edge length. ``None`` uses the diameter of the point cloud
        (default ``None``).
    
    Examples
    --------
    Build a complex from four points in the plane:
    
    >>> import numpy as np
    >>> import synaplex
    >>> pts = np.array([[0, 0], [1, 0], [0, 1], [1, 1]], dtype=np.float64)
    >>> cpx = synaplex.complex.VietorisRipsComplex(pts, max_dim=2)
    >>> cpx.dimension()
    2
    >>> cpx.len()  # total number of simplices
    11
    
    Restrict by a distance threshold:
    
    >>> cpx = synaplex.complex.VietorisRipsComplex(pts, threshold=1.0)
    >>> cpx.threshold()
    1.0
    """
    def __new__(cls, points: numpy.typing.NDArray[numpy.float64], max_dim: builtins.int = 2, threshold: typing.Optional[builtins.float] = None) -> VietorisRipsComplex:
        r"""
        Create a new Vietoris-Rips complex from a point cloud.
        
        Parameters
        ----------
        points : numpy.ndarray
            Point cloud of shape ``(n_points, n_features)``.
        max_dim : int, optional
            Maximum simplex dimension (default ``2``).
        threshold : float or None, optional
            Maximum edge length (default ``None`` — uses full diameter).
        
        Returns
        -------
        VietorisRipsComplex
            The constructed simplicial complex.
        """
    def len(self) -> builtins.int:
        r"""
        Return the total number of simplices in the complex.
        
        Returns
        -------
        int
            Total simplex count across all dimensions.
        
        Examples
        --------
        >>> cpx.len()
        11
        """
    def count_by_dim(self, dim: builtins.int) -> builtins.int:
        r"""
        Count the simplices of a given dimension.
        
        Parameters
        ----------
        dim : int
            The dimension to count (0 = vertices, 1 = edges, 2 = triangles, ...).
        
        Returns
        -------
        int
            Number of simplices in that dimension.
        
        Examples
        --------
        >>> cpx.count_by_dim(0)  # number of vertices
        4
        >>> cpx.count_by_dim(1)  # number of edges
        6
        """
    def dimension(self) -> builtins.int:
        r"""
        Return the maximum dimension of the complex.
        
        Returns
        -------
        int
            The highest dimension of any simplex in the complex.
        
        Examples
        --------
        >>> cpx.dimension()
        2
        """
    def threshold(self) -> builtins.float:
        r"""
        Return the filtration threshold used to build the complex.
        
        Returns
        -------
        float
            The maximum edge length in the filtration.
        
        Examples
        --------
        >>> cpx.threshold()
        1.4142135623730951
        """
    def __repr__(self) -> builtins.str: ...

