# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405
r"""
Synaplex — high-performance Topological Data Analysis engine for neural networks.

Synaplex provides Rust-accelerated persistent homology, Mapper, and
topological neural-network analysis tools with a Pythonic interface.

Submodules
----------
homology : Persistent cohomology computation.
neural   : Topological signatures for activations and weights.
complex  : Vietoris-Rips simplicial complex construction.
distance : Pairwise distance matrix computation.
diagram  : Bottleneck and Wasserstein distances on persistence diagrams.
mapper   : The Mapper pipeline for graph-based data summarisation.
"""

from synaplex.homology import betti_numbers, persistence_diagram, test_fn
from . import complex
from . import diagram
from . import distance
from . import homology
from . import mapper
from . import neural
__all__ = [
    "betti_numbers",
    "complex",
    "diagram",
    "distance",
    "homology",
    "mapper",
    "neural",
    "persistence_diagram",
    "test_fn",
]

