# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405
r"""
Distance matrix computation.

Compute dense pairwise distance matrices with Euclidean, cosine, or
Manhattan metrics. Computation is parallelised with Rayon.
"""

import builtins
import numpy
import numpy.typing
__all__ = [
    "distance_matrix",
]

def distance_matrix(points: numpy.typing.NDArray[numpy.float64], metric: builtins.str = 'euclidean') -> numpy.typing.NDArray[numpy.float64]:
    r"""
    Compute the pairwise distance matrix for a point cloud.
    
    Returns the upper-triangular entries of the symmetric distance matrix
    stored as a flat array (condensed form, same layout as
    ``scipy.spatial.distance.pdist``).
    
    Parameters
    ----------
    points : numpy.ndarray
        Input point cloud of shape ``(n_points, n_features)``.
    metric : str, optional
        Distance metric to use (default ``"euclidean"``).
        Supported values: ``"euclidean"``, ``"cosine"``, ``"manhattan"``.
    
    Returns
    -------
    numpy.ndarray
        1-D array of length ``n_points * (n_points - 1) / 2`` containing the
        upper-triangle of the pairwise distance matrix.
    
    Raises
    ------
    ValueError
        If *metric* is not one of the supported values.
    
    Examples
    --------
    >>> import numpy as np
    >>> import synaplex
    >>> pts = np.array([[0, 0], [3, 0], [0, 4]], dtype=np.float64)
    >>> d = synaplex.distance.distance_matrix(pts)
    >>> d.shape
    (3,)
    >>> d[0]  # distance between point 0 and point 1
    3.0
    
    Use cosine distance:
    
    >>> d = synaplex.distance.distance_matrix(pts, metric="cosine")
    """

