# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405
r"""
Topological analysis tools for neural network layers.

Analyse the shape of activation spaces, weight matrices, and compare
the topological signatures of different layers.
"""

import builtins
import numpy
import numpy.typing
import typing
__all__ = [
    "analyze_activations",
    "analyze_weights",
    "compare_layers",
]

def analyze_activations(activations: numpy.typing.NDArray[numpy.float64], max_dim: builtins.int = 1, subsample: typing.Optional[builtins.int] = None, modulus: builtins.int = 2) -> numpy.typing.NDArray[numpy.float64]:
    r"""
    Compute the topological signature of a neural network layer's activations.
    
    Treats each row of the activation matrix as a point in feature space,
    builds a Vietoris-Rips filtration on the resulting point cloud, and
    returns the persistence diagram summarising the topology.
    
    Parameters
    ----------
    activations : numpy.ndarray
        Activation matrix of shape ``(n_samples, n_neurons)`` — one row per
        input sample, one column per neuron in the layer.
    max_dim : int, optional
        Maximum homological dimension (default ``1``).
    subsample : int or None, optional
        If set, randomly subsample to this many points before computing
        (useful for large batches). ``None`` keeps all points (default).
    modulus : int, optional
        Prime modulus for the coefficient field Z/pZ (default ``2``).
    
    Returns
    -------
    numpy.ndarray
        Persistence diagram as an array of shape ``(n_pairs, 3)`` where each
        row is ``[dimension, birth, death]``.
    
    Examples
    --------
    Analyse the topology of a hidden layer with 128 neurons on 500 samples:
    
    >>> import numpy as np
    >>> import synaplex
    >>> activations = np.random.randn(500, 128)
    >>> dgm = synaplex.neural.analyze_activations(activations, max_dim=1)
    >>> dgm.shape[1]
    3
    
    Subsample for faster computation:
    
    >>> dgm = synaplex.neural.analyze_activations(activations, subsample=100)
    """

def analyze_weights(weights: numpy.typing.NDArray[numpy.float64], max_dim: builtins.int = 1, row_wise: builtins.bool = True, modulus: builtins.int = 2) -> numpy.typing.NDArray[numpy.float64]:
    r"""
    Compute the topological signature of a weight matrix.
    
    Interprets the weight matrix as a collection of row (or column) vectors
    in parameter space, computes the persistence diagram of the resulting
    point cloud, revealing clusters, loops, and higher-dimensional structure.
    
    Parameters
    ----------
    weights : numpy.ndarray
        Weight matrix of shape ``(n_out, n_in)`` (or transposed if
        ``row_wise=False``).
    max_dim : int, optional
        Maximum homological dimension (default ``1``).
    row_wise : bool, optional
        If ``True`` (default), each *row* is treated as a point.
        If ``False``, each *column* is treated as a point.
    modulus : int, optional
        Prime modulus for the coefficient field Z/pZ (default ``2``).
    
    Returns
    -------
    numpy.ndarray
        Persistence diagram of shape ``(n_pairs, 3)`` with columns
        ``[dimension, birth, death]``.
    
    Examples
    --------
    Analyse a 256×128 weight matrix (e.g. a linear layer):
    
    >>> import numpy as np
    >>> import synaplex
    >>> W = np.random.randn(256, 128)
    >>> dgm = synaplex.neural.analyze_weights(W, max_dim=1)
    >>> dgm.shape[1]
    3
    
    Analyse column-wise (one point per input neuron):
    
    >>> dgm = synaplex.neural.analyze_weights(W, row_wise=False)
    """

def compare_layers(layers: typing.Sequence[numpy.typing.NDArray[numpy.float64]], max_dim: builtins.int = 1) -> numpy.typing.NDArray[numpy.float64]:
    r"""
    Compare the topology of multiple neural network layers.
    
    Computes the persistence diagram for each layer's activations, then
    returns a pairwise bottleneck distance matrix measuring how
    topologically different the layers are.
    
    Parameters
    ----------
    layers : list[numpy.ndarray]
        A list of activation matrices, one per layer. Each array has shape
        ``(n_samples, n_neurons_in_layer)``.
    max_dim : int, optional
        Maximum homological dimension (default ``1``).
    
    Returns
    -------
    numpy.ndarray
        Symmetric distance matrix of shape ``(n_layers, n_layers)`` where
        entry ``(i, j)`` is the bottleneck distance between the persistence
        diagrams of layer *i* and layer *j*.
    
    Examples
    --------
    Compare three layers of a neural network:
    
    >>> import numpy as np
    >>> import synaplex
    >>> layers = [
    ...     np.random.randn(200, 64),   # layer 1
    ...     np.random.randn(200, 128),  # layer 2
    ...     np.random.randn(200, 64),   # layer 3
    ... ]
    >>> dist = synaplex.neural.compare_layers(layers, max_dim=1)
    >>> dist.shape
    (3, 3)
    >>> dist[0, 0]  # distance of a layer to itself
    0.0
    """

