# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405
r"""
Persistent cohomology computation.

This module computes persistence diagrams and Betti numbers from
point clouds using cohomology, clearing optimisation, and arbitrary
Z/pZ coefficients.
"""

import builtins
import numpy
import numpy.typing
import typing
__all__ = [
    "betti_numbers",
    "persistence_diagram",
    "test_fn",
]

def betti_numbers(points: numpy.typing.NDArray[numpy.float64], at_filtration: builtins.float, max_dim: builtins.int = 1, threshold: typing.Optional[builtins.float] = None, modulus: builtins.int = 2) -> builtins.list[builtins.int]:
    r"""
    Compute Betti numbers at a given filtration value.
    
    The k-th Betti number counts the number of k-dimensional topological
    features (connected components, loops, voids, ...) that are alive at the
    specified filtration value.
    
    Parameters
    ----------
    points : numpy.ndarray
        Input point cloud of shape ``(n_points, n_features)``.
    at_filtration : float
        Filtration value at which to count alive features.
    max_dim : int, optional
        Maximum homological dimension (default ``1``).
    threshold : float or None, optional
        Maximum filtration value (default ``None``).
    modulus : int, optional
        Prime modulus for the coefficient field Z/pZ (default ``2``).
    
    Returns
    -------
    list[int]
        A list of Betti numbers ``[beta_0, beta_1, ..., beta_{max_dim}]``.
    
    Examples
    --------
    >>> import numpy as np
    >>> import synaplex
    >>> pts = np.array([[0, 0], [1, 0], [0, 1], [1, 1]], dtype=np.float64)
    >>> betti = synaplex.betti_numbers(pts, at_filtration=1.5)
    >>> len(betti)  # max_dim+1 entries
    2
    >>> betti[0]  # number of connected components
    1
    """

def persistence_diagram(points: numpy.typing.NDArray[numpy.float64], max_dim: builtins.int = 1, threshold: typing.Optional[builtins.float] = None, modulus: builtins.int = 2, cocycles: builtins.bool = False) -> typing.Any:
    r"""
    Compute persistent cohomology of a point cloud.
    
    Builds a Vietoris-Rips filtration from the Euclidean distance matrix of the
    input points, then computes persistent cohomology with coefficients in Z/pZ.
    
    Parameters
    ----------
    points : numpy.ndarray
        Input point cloud of shape ``(n_points, n_features)``.
    max_dim : int, optional
        Maximum homological dimension to compute (default ``1``).
        Dimension 0 captures connected components, dimension 1 captures loops, etc.
    threshold : float or None, optional
        Maximum filtration value (edge length). ``None`` means no cutoff
        (default ``None``).
    modulus : int, optional
        Prime modulus for the coefficient field Z/pZ (default ``2``).
        Use a different prime (e.g. 3, 5, 7) to detect torsion.
    cocycles : bool, optional
        If ``True``, also return cocycle representatives (default ``False``).
    
    Returns
    -------
    numpy.ndarray or dict
        * If ``cocycles=False``: an array of shape ``(n_pairs, 3)`` where each
          row is ``[dimension, birth, death]``.
        * If ``cocycles=True``: a ``dict`` with keys ``"diagram"`` (the array)
          and ``"cocycles"`` (nested list of cocycle representatives).
    
    Examples
    --------
    Compute H0 and H1 of a small point cloud:
    
    >>> import numpy as np
    >>> import synaplex
    >>> pts = np.array([[0, 0], [1, 0], [0, 1], [1, 1]], dtype=np.float64)
    >>> dgm = synaplex.persistence_diagram(pts, max_dim=1)
    >>> dgm.shape[1]
    3
    
    Compute with cocycle representatives:
    
    >>> result = synaplex.persistence_diagram(pts, max_dim=1, cocycles=True)
    >>> result["diagram"].shape[1]
    3
    
    Use Z/3Z coefficients to detect torsion:
    
    >>> dgm = synaplex.persistence_diagram(pts, max_dim=1, modulus=3)
    """

def test_fn(a: builtins.int, b: builtins.int = 2, c: builtins.int = 3) -> builtins.int:
    r"""
    Test function to verify that the native extension loads correctly.
    
    Parameters
    ----------
    a : int
        First value.
    b : int, optional
        Second value (default ``2``).
    c : int, optional
        Third value (default ``3``).
    
    Returns
    -------
    int
        The sum ``a + b + c``.
    
    Examples
    --------
    >>> import synaplex
    >>> synaplex.test_fn(1)
    6
    >>> synaplex.test_fn(1, b=10, c=20)
    31
    """

