# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405
r"""
The Mapper pipeline for topological graph summarisation.

Mapper projects data through a filter function, covers the range
with overlapping intervals, clusters within each interval, and
builds the nerve complex — a graph that reveals the global shape
of the data.
"""

import builtins
import numpy
import numpy.typing
import typing
__all__ = [
    "mapper",
]

def mapper(points: numpy.typing.NDArray[numpy.float64], filter_values: numpy.typing.NDArray[numpy.float64], num_intervals: builtins.int = 10, overlap: builtins.float = 0.3, clustering: builtins.str = 'single_linkage', clustering_threshold: typing.Optional[builtins.float] = None, cover_type: builtins.str = 'uniform') -> dict:
    r"""
    Run the Mapper pipeline to build a topological graph of a dataset.
    
    Mapper is a tool from topological data analysis that produces a
    simplified graph representation of high-dimensional data. It works by:
    
    1. Projecting data through a *filter function* (user-supplied values).
    2. Covering the filter range with overlapping intervals.
    3. Clustering within each interval.
    4. Building the *nerve* — a graph whose nodes are clusters and whose
       edges connect clusters that share data points.
    
    Parameters
    ----------
    points : numpy.ndarray
        Input data of shape ``(n_points, n_features)``.
    filter_values : numpy.ndarray
        1-D array of length ``n_points`` with the filter function evaluated
        on each point (e.g. eccentricity, density, a PCA coordinate, …).
    num_intervals : int, optional
        Number of intervals in the cover (default ``10``).
    overlap : float, optional
        Fractional overlap between consecutive intervals, in ``(0, 1)``
        (default ``0.3``).
    clustering : str, optional
        Clustering algorithm: ``"single_linkage"`` (default) or
        ``"dbscan"``.
    clustering_threshold : float or None, optional
        Distance threshold for clustering. For single-linkage: cut height.
        For DBSCAN: the ``eps`` parameter (default ``None`` — auto).
    cover_type : str, optional
        Cover strategy: ``"uniform"`` (default) or ``"balanced"``
        (quantile-based, equal point counts per interval).
    
    Returns
    -------
    dict
        A dictionary with keys:
    
        * ``"nodes"`` — list of lists of point indices per node.
        * ``"num_nodes"`` — total number of nodes.
        * ``"num_edges"`` — total number of edges.
        * ``"edges"`` — list of ``(source, target, shared_count)`` tuples.
    
    Raises
    ------
    ValueError
        If *clustering* or *cover_type* is not a recognised value.
    
    Examples
    --------
    Build a Mapper graph from 2-D data using the first coordinate as filter:
    
    >>> import numpy as np
    >>> import synaplex
    >>> pts = np.random.randn(500, 2)
    >>> filt = pts[:, 0]  # use x-coordinate as filter
    >>> g = synaplex.mapper.mapper(pts, filt, num_intervals=15, overlap=0.25)
    >>> g["num_nodes"] > 0
    True
    >>> len(g["edges"]) >= 0
    True
    
    Use DBSCAN clustering with a balanced cover:
    
    >>> g = synaplex.mapper.mapper(
    ...     pts, filt,
    ...     clustering="dbscan",
    ...     clustering_threshold=0.5,
    ...     cover_type="balanced",
    ... )
    """

